# Generated by Django 5.2.18 on 2026-10-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('vinyl', 'Vinyl'), ('cd', 'CD'), ('cassette', 'Cassette'), ('digital', 'Digital')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('catalog_number', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('edition', models.CharField(blank=True, max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='collection.album')),
            ],
        ),
    ]
